// Rochdale Daily homepage feed request-time guard.
// The static feed is generated by the scraper, but this Function is the final
// publication boundary for /articles/frontpage.json. Editorially removed
// stories are filtered here as defence in depth so a stale deployment/cache or
// race cannot leave a dead/403 story card visible on the paper.

const LIVE_UNTIL = Date.parse('2026-08-09T01:30:00+01:00');
// The takedown workflow writes story_blocklist.json. This Function used to keep
// its own copy of the list, which meant a story removed through one route was
// still served by the other, and nothing kept the two in step. It now reads the
// committed blocklist at request time. The names below remain only as a
// last-resort fallback for the case where that file cannot be read at all.
const FALLBACK_BLOCKED_SLUGS = new Set([
  'crowds-gather-at-rochdale-town-hall-this-afternoon',
  'james-and-georgina-celebrate-their-wedding-at-whitworth-estate',
  'new-stone-circle-installed-near-rochdale',
  'rochdale-borough-council-licensing-sub-committee-meeting-scheduled-for-may-2026',
  'rochdale-valiant-launches-new-media-portal',
  'rochdale-valiant-launches-new-media-portal-for-community-engagement',
  'rochdale-valiant-launches-new-media-portal-for-community-news',
  'rochdale-valiant-launches-new-media-portal-for-local-community',
  'rochdale-valiant-launches-new-media-portal-for-local-news',
  'rochdale-valiant-launches-new-media-portal-to-enhance-community-engagement',
  'rochdale-weather-forecast-sunny-intervals-expected-this-week',
  'rochdale-weather-forecast-warm-and-sunny-days-ahead',
  'sunny-weather-expected-in-rochdale-this-week',
  'traffic-incidents-reported-in-rochdale',
  'traffic-update-for-rochdale-current-conditions-and-alerts',
  'voters-urged-to-support-marlon-west-in-greater-manchester-election',
  'walking-the-rochdale-canal-a-scenic-journey-from-brearley-bridge-to-luddendenfoo'
]);

// Subject-level blocks. A slug list can only stop the exact pages that already
// exist; the scraper regenerates the same story under a new slug every time the
// headline is reworded, which is how six near-identical pages got published.
// The scraper matches story_blocklist.json title_patterns as a lowercase
// substring of the headline -- this Function now does the same, so both ends of
// the pipeline block on the same rule.
const FALLBACK_BLOCKED_TITLE_PATTERNS = ['rochdale valiant'];

function normaliseSlug(value) {
  return String(value == null ? '' : value)
    .replace(/^\.\.\//, '').replace(/\.html$/i, '').trim().toLowerCase();
}

/** Read the committed blocklist. Falls back to the names above if unreadable. */
async function loadBlocklist(env, requestUrl) {
  const slugs = new Set(FALLBACK_BLOCKED_SLUGS);
  const patterns = new Set(FALLBACK_BLOCKED_TITLE_PATTERNS);
  try {
    const url = new URL('/story_blocklist.json', requestUrl);
    const response = await env.ASSETS.fetch(url);
    if (!response.ok) return { slugs, patterns };
    const data = await response.json();
    const listed = Array.isArray(data) ? data : (data && data.slugs);
    if (Array.isArray(listed)) {
      for (const entry of listed) {
        // Keep the fallback names too: a slug removed from the committed file
        // by accident should not quietly come back onto the front page.
        const slug = normaliseSlug(entry && entry.slug ? entry.slug : entry);
        if (slug) slugs.add(slug);
      }
    }
    const titles = data && !Array.isArray(data) ? data.title_patterns : null;
    if (Array.isArray(titles)) {
      for (const entry of titles) {
        const pattern = String(entry == null ? '' : entry).trim().toLowerCase();
        if (pattern) patterns.add(pattern);
      }
    }
  } catch (_) { /* fall through to the fallback sets */ }
  return { slugs, patterns };
}

function isBlocked(article, blocklist) {
  if (blocklist.slugs.has(slugOf(article))) return true;
  const title = String(article?.title || '').trim().toLowerCase();
  if (!title) return false;
  for (const pattern of blocklist.patterns) {
    if (title.includes(pattern)) return true;
  }
  return false;
}

// --------------------------------------------------------------------------
// Breaking news from the GMP watcher.
//
// scraper/gmp_watch.py writes breaking.json within a minute of GMP posting.
// Reading it here, at request time, is what makes that minute count: the story
// reaches the front page as soon as Pages has the commit, with no site rebuild
// and without queueing behind a scrape that holds rd-site-writer for up to 45
// minutes. This is the same trick the live-festival story below already uses --
// a story served from the edge that is not in the static feed at all.
//
// Only entries the watcher marked 'live' appear. Anything it held for legal
// review stays in the file and stays off the site.
// --------------------------------------------------------------------------

const BREAKING_KICKER = 'BREAKING';

function breakingToArticle(entry, nowIso) {
  const slug = normaliseSlug(entry.slug);
  const quote = String(entry.quote || '').trim();
  const attribution = String(entry.attribution || 'Greater Manchester Police said:');
  const sourceUrl = String(entry.source_url || '');
  const paragraphs = quote
    .split(/\n{2,}/)
    .map(p => p.trim())
    .filter(Boolean)
    .map(p => `<p>${escapeHtml(p)}</p>`)
    .join('');
  return {
    id: `breaking:${slug}`,
    // articles/${slug}.html is how the homepage builds every card link, so
    // escaping one level up puts the reader on the Function-rendered page.
    slug: `../breaking/${slug}`,
    story_key: `breaking:${slug}`,
    title: String(entry.title || ''),
    excerpt: quote.slice(0, 220),
    content_html: `<p><strong>${escapeHtml(attribution)}</strong></p>${paragraphs}`,
    area: String(entry.area || 'rochdale'),
    category: String(entry.category || 'crime'),
    types: ['news'],
    source_kind: 'official-statement',
    status: 'published',
    published_at: entry.published_at,
    first_published_at: entry.published_at,
    last_updated_at: entry.published_at,
    scraped_at: entry.detected_at || entry.published_at,
    source_name: String(entry.source_name || 'Greater Manchester Police'),
    source_url: sourceUrl,
    source_names: [String(entry.source_name || 'Greater Manchester Police')],
    source_urls: sourceUrl ? [sourceUrl] : [],
    image_url: String(entry.image_url || 'assets/img/cards/police.jpg'),
    image_credit: 'Rochdale Daily',
    byline: String(entry.byline || 'Rochdale Daily'),
    kicker: BREAKING_KICKER,
    is_ongoing: true,
    ongoing_label: BREAKING_KICKER,
    breaking: true,
    police_matter: true,
    developing: true,
    rewrite_quality_checked: true,
    publication_route: 'gmp-breaking-watch'
  };
}

function escapeHtml(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

async function loadBreaking(env, requestUrl, now) {
  try {
    const url = new URL('/breaking.json', requestUrl);
    const response = await env.ASSETS.fetch(url);
    if (!response.ok) return [];
    const data = await response.json();
    const items = Array.isArray(data) ? data : (data && data.items);
    if (!Array.isArray(items)) return [];
    return items
      .filter(entry => entry && entry.status === 'live' && entry.title && entry.slug)
      .filter(entry => {
        const expires = Date.parse(entry.expires_at || '');
        return !Number.isFinite(expires) || expires > now.getTime();
      })
      .sort((a, b) => Date.parse(b.published_at || 0) - Date.parse(a.published_at || 0));
  } catch (_) {
    return [];
  }
}

function storyTime(article) {
  const value = article?.first_published_at || article?.published_at || article?.last_updated_at || '';
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function slugOf(article) {
  return normaliseSlug(article?.slug);
}

function liveStory(nowIso) {
  return {
    id: 'feel-good-festival-2026-live',
    slug: '../feel-good-live',
    story_key: 'editorial:feel-good-festival-2026-live',
    title: 'LIVE: Rochdale Feel Good Festival 2026 — updates throughout the day',
    excerpt: 'Follow Rochdale Daily live from Feel Good Festival 2026, with Gabrielle, Ash, Starsailor, town-centre updates, timings, food and drink, travel and everything happening across Rochdale.',
    content_html: '<p>Follow Rochdale Daily’s rolling live coverage of Feel Good Festival 2026 throughout Saturday 8 August.</p>',
    area: 'rochdale', category: 'news', types: ['news'], source_kind: 'editorial', status: 'published',
    published_at: '2026-08-08T07:00:00Z', first_published_at: '2026-08-08T07:00:00Z', last_updated_at: nowIso, scraped_at: nowIso,
    source_name: 'Rochdale Daily', source_url: 'https://rochdaledaily.co.uk/feel-good-live.html', source_names: ['Rochdale Daily'], source_urls: ['https://rochdaledaily.co.uk/feel-good-live.html'],
    image_url: 'assets/img/cards/rochdale-town-hall.jpg', image_credit: 'Rochdale Daily', byline: 'Rochdale Daily', manual_article: true,
    editorial_lock: true, publication_route: 'editorial-live', rewrite_quality_checked: true, featured: true, force_lead: true,
    is_ongoing: true, ongoing_label: 'LIVE', update_count: 5, frontpage_rank: 0, frontpage_priority: 10000, slot: 'lead'
  };
}

export async function onRequest(context) {
  const { request, env } = context;
  const assetUrl = new URL(request.url);
  const upstream = await env.ASSETS.fetch(assetUrl);
  if (!upstream.ok) return upstream;

  let data;
  try { data = await upstream.json(); } catch (_) { return upstream; }
  if (!data || !Array.isArray(data.articles)) {
    return new Response(JSON.stringify(data), { status: 200, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' } });
  }

  const now = new Date();
  const nowIso = now.toISOString();
  const blocklist = await loadBlocklist(env, request.url);
  let articles = data.articles.filter(a => a && a.id !== 'feel-good-festival-2026-live' && !isBlocked(a, blocklist));
  articles.sort((a, b) => storyTime(b) - storyTime(a));

  // Breaking entries go above the sorted feed but below a running live blog.
  // The blocklist applies to them too: a story you have taken down must not
  // come back through the breaking door.
  const breakingEntries = await loadBreaking(env, request.url, now);

  // Once the pipeline has published its own article from the same GMP post,
  // the canonical version wins and the breaking card steps aside -- otherwise
  // the front page carries the story twice, the stub above the real thing.
  const publishedSourceUrls = new Set();
  for (const article of articles) {
    for (const url of [article.source_url, ...(Array.isArray(article.source_urls) ? article.source_urls : [])]) {
      if (url) publishedSourceUrls.add(String(url).trim());
    }
  }
  const breakingArticles = breakingEntries
    .filter(entry => !publishedSourceUrls.has(String(entry.source_url || '').trim()))
    .map(entry => breakingToArticle(entry, nowIso))
    .filter(article => !isBlocked(article, blocklist));
  if (breakingArticles.length) articles.unshift(...breakingArticles);

  if (now.getTime() <= LIVE_UNTIL) articles.unshift(liveStory(nowIso));

  articles.forEach((article, index) => {
    article.frontpage_rank = index;
    article.frontpage_priority = index === 0 ? 10000 : Math.max(1, 1000 - index);
    article.slot = index === 0 ? 'lead' : index === 1 ? 'secondary-1' : index === 2 ? 'secondary-2' : '';
  });

  data.articles = articles;
  data.count = articles.length;
  data.generated_at = nowIso;
  if (articles[0]?.id === 'feel-good-festival-2026-live') {
    const liveTitle = articles[0].title;
    const existing = String(data.breaking || '').trim();
    data.breaking = liveTitle + (existing && !existing.includes(liveTitle) ? '     •     BREAKING     •     ' + existing : '');
  }

  // Put breaking headlines in the ticker too. A card the reader has to scroll
  // to is not really breaking.
  if (breakingArticles.length) {
    const headlines = breakingArticles.map(a => a.title).filter(Boolean);
    const existing = String(data.breaking || '').trim();
    const fresh = headlines.filter(title => !existing.includes(title));
    if (fresh.length) {
      data.breaking = [...fresh, existing].filter(Boolean).join('     •     BREAKING     •     ');
    }
  }
  data.breaking_count = breakingArticles.length;

  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'no-store, no-cache, must-revalidate, max-age=0',
      'x-rd-homepage-fix': 'editorial-blocklist-v2'
    }
  });
}
